detector: YOLO_Ultralytics
conf: 0.5
iou: 0.7
imgsz: 640
half: False
min_width: 35
classes: null # NULL=Null=null is None in Python
device: 0
max_det: 100
line_width: 500
model_file: data/detectors/yolov11n.pt
